"""empty message

Revision ID: 3030d1dc1673
Revises: 9808f950e798
Create Date: 2024-10-08 22:50:40.887283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3030d1dc1673'
down_revision = '9808f950e798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_firstname', sa.String(), nullable=True),
    sa.Column('user_lastname', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('user_privilege', sa.String(), server_default='standard', nullable=False),
    sa.Column('user_status', sa.String(), server_default='active', nullable=False),
    sa.Column('user_dateCreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('contactlist',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_room', sa.String(), nullable=False),
    sa.Column('contact_status', sa.String(), server_default='contact', nullable=False),
    sa.Column('contact_dateCreated', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contactuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contactuser_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_message', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('message_dateCreated', sa.DateTime(), nullable=False),
    sa.Column('message_sender', sa.Integer(), nullable=True),
    sa.Column('message_sentto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_sender'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['message_sentto'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('contactlist')
    op.drop_table('user')
    # ### end Alembic commands ###
